- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - basic-check-spec
    image: quay.io/operator-framework/scorecard-test@sha256:cc84b78999e6edef85de2d10bc880588f6994c81dd5e012610d84efc06ab98b9
    labels:
      suite: basic
      test: basic-check-spec-test
