# permissions for end users to view codegens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codegen-viewer-role
rules:
- apiGroups:
  - apps.apimatic.io
  resources:
  - codegens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.apimatic.io
  resources:
  - codegens/status
  verbs:
  - get
