# permissions for end users to edit codegens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codegen-editor-role
rules:
- apiGroups:
  - apps.apimatic.io
  resources:
  - codegens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.apimatic.io
  resources:
  - codegens/status
  verbs:
  - get
